stages:
    - build
    - deploy

build:
    stage: build
    image: gradle:jdk11
    script:
        - cd backend
        - mkdir sources
        - mv src/* sources
        - mkdir -p src/main/java
        - mv sources/* src/main/java
        - gradle init build
    artifacts:
        paths:
            - $CI_PROJECT_DIR/backend/build/libs/backend.jar

deploy:
    stage: deploy
    image: openjdk:11
    script:
        - apt install -y curl
        - curl -sL https://deb.nodesource.com/setup_14.x | bash -
        - apt install -y nodejs
        - curl -L https://www.npmjs.com/install.sh | sh
        - npm install -g heroku
        - heroku plugins:install heroku-cli-deploy
        - heroku deploy:jar $CI_PROJECT_DIR/backend/build/libs/backend.jar --app g14-vidampark
    artifacts:
        paths:
            - $CI_PROJECT_DIR/backend/build/libs/backend.jar