stages:
    - build
    - merge
    - deploy

backend:
    stage: build
    image: gradle:jdk11
    script:
        - gradle build
    artifacts:
        paths:
            - $CI_PROJECT_DIR/build/libs/g14-digital-entertainment.jar
    when:  
        manual

frontend:
    stage: build
    image: node:latest
    script:
        - apt update
        - apt install -y zip
        - cd src/main/frontend/rework
        - npm install
        - npm run build
        - zip -r frontend.zip build
    artifacts:
        paths:
            - $CI_PROJECT_DIR/src/main/frontend/rework/frontend.zip
    when:  
        manual

merge:
    stage: merge
    script:
        - apt update
        - apt install -y zip
        - cd $CI_PROJECT_DIR/build/libs/
        - zip -ur g14-digital-entertainment.jar $CI_PROJECT_DIR/src/main/frontend/rework/frontend.zip
    artifacts:
        paths:
            - $CI_PROJECT_DIR/build/libs/g14-digital-entertainment.jar
    when:
        manual

deploy:
    stage: deploy
    image: openjdk:11
    script:
        - apt install -y curl
        - curl -sL https://deb.nodesource.com/setup_14.x | bash -
        - apt install -y nodejs
        - curl -L https://www.npmjs.com/install.sh | sh
        - npm install -g heroku
        - heroku plugins:install heroku-cli-deploy
        - heroku deploy:jar $CI_PROJECT_DIR/build/libs/g14-digital-entertainment.jar --jdk 11 --app g14-vidampark
    when:  
        manual
