stages:
    - build
#    - deploy

build:
    stage: build
    services:
        - gradle:latest
    script:
        - cd backend
        - mkdir sources
        - mv src/* sources
        - mkdir -p src/main/java
        - mv sources/* src/main/java
        #- docker run --rm -v "$PWD":/home/gradle/project -w /home/gradle/project gradle gradle init build
        - gradle help
    artifacts:
        paths:
            - backend/build/libs/project.jar

#deploy:
#    stage: deploy
#    script:
#        - mkdir public
#        - mv frontend/src/* public
#    artifacts:
#        paths:
#            - public
#    only:
#        - master