stages:
    - build
#    - deploy

build:
    stage: build
    image: gradle:jdk11
    script:
        - cd backend
        - mkdir sources
        - mv src/* sources
        - mkdir -p src/main/java
        - mv sources/* src/main/java
        - gradle init build
        - ls -R
    artifacts:
        paths:
            - backend/build/libs/backend.jar

#deploy:
#    stage: deploy
#    script:
#        - mkdir public
#        - mv frontend/src/* public
#    artifacts:
#        paths:
#            - public
#    only:
#        - master