stages:
    - build
#    - deploy

build:
    stage: build
    image: gradle:jdk11
    services:
        - node:latest
    script:
        - cd backend
        - mkdir sources
        - mv src/* sources
        - mkdir -p src/main/java
        - mv sources/* src/main/java
        - gradle init build
        - npm install -g heroku
        - heroku plugins:install heroku-cli-deploy
        - heroku deploy:jar backend/build/libs/backend.jar --app g14-vidampark
    artifacts:
        paths:
            - backend/build/libs/backend.jar

#deploy:
#    stage: deploy
#    script:
#        - mkdir public
#        - mv frontend/src/* public
#    artifacts:
#        paths:
#            - public
#    only:
#        - master
