stages:
    - build
    - deploy

build:
    stage: build
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - pwd

deploy:
    stage: deploy
    script:
        - mkdir public
        - mv frontend/src/* public
    artifacts:
        paths:
            - public
    only:
        - master